server:
  port: 12345


websocket:
  uri: ws://116.62.63.164:24546/wsServices

spring:
  data:
    mongodb:
      host: 175.24.147.229
      port: 27018
      database: detection
      username: dev
      password: dev890
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

# 日志文件位置
logging:
  file:
    path: "./logs/"

# 验证码相关信息
kaptcha:
  border:
    have: "no"
    color: white

  producer:
    impl: com.google.code.kaptcha.impl.DefaultKaptcha

  textproducer:
    impl: com.google.code.kaptcha.text.impl.DefaultTextCreator
    chars: # char
      length: 4
      space: 2
    font:
      color: 68,194,253
      size: 40
      names: Arial, Courier

  word:
    impl: com.google.code.kaptcha.text.impl.DefaultWordRenderer

  image:
    width: 150
    height: 50

  background:
    impl: com.google.code.kaptcha.impl.DefaultBackground
    clear:
      from: white
      to: white

  noise:
    color: 178,219,255
    impl: com.google.code.kaptcha.impl.DefaultNoise

  obscurificator:
    impl: com.google.code.kaptcha.impl.ShadowGimpy

  session:
    key: code
    date: date